[package]
name = "lambda-web"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambda_http = "0.4"
tokio = "1"
serde = "1"
http = "0.2"
serde_json = "1"
